Подключение через гит хаб

In [ ]:
!git clone https://github.com/Karperash/Metod-HIVES.git
%cd Metod-HIVES


Cloning into 'Metod-HIVES'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 2), reused 17 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (17/17), 17.60 KiB | 300.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
/content/Metod-HIVES/Metod-HIVES


In [ ]:
!pip -q install numpy


In [ ]:
!python main.py input.json



Сырые веса критериев γ:
[21.25 12.14 11.34 23.5  16.4  10.18]

Нормированные веса критериев γ' (в сумме = 100):
[22.41 12.8  11.96 24.78 17.3  10.74]

Итоговые баллы альтернатив:
  A1: 3760.56
  A2: 5036.7
  A3: 3411.02
  A4: 7688.34
  A5: 3727.13
  A6: 4535.3
  A7: 3905.38
  A8: 3135.52
  A9: 4840.21
  A10: 4593.63
  A11: 3733.03
  A12: 4333.11
  A13: 7312.27
  A14: 6201.87
  A15: 3652.74

Ранжирование альтернатив (1-based):
[ 4 13 14  2  9 10  6 12  7  1 11  5 15  3  8]
